apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-world-dropwizard
  labels:
    backstage.io/kubernetes-id: hello-world-dropwizard
spec:
  selector:
    matchLabels:
      app: hello-world-dropwizard
  replicas: 2
  revisionHistoryLimit: 0 # Default to 10 if not specified
  template:
    metadata:
      labels:
        app: hello-world-dropwizard
        "backstage.io/kubernetes-id": "hello-world-dropwizard"
    spec:
      containers:
      - image: nicolasfagotti/hello-world-dropwizard:1.17.0
        name: hello-world-dropwizard
  strategy:
    canary:
#      trafficRouting:
#        istio:
#          virtualService:
#            name: rollout-vsvc # required
#            routes:
#            - primary
      steps:
      - experiment:
          duration: 3m
          templates:
          - name: baseline
            specRef: stable
#            weight: 5
          - name: canary
            specRef: canary
#            weight: 5
          analyses:
          - name: aca-analyzer
            templateName: aca-analyzer
            requiredForCompletion: true
            args:
            - name: start-time
              value: "{{ experiment.availableAt }}"
            - name: end-time
              value: "{{ experiment.finishedAt }}"
            - name: stable-hash
              valueFrom:
                podTemplateHashValue: Stable
            - name: canary-hash
              valueFrom:
                podTemplateHashValue: Latest
          - name: mann-whitney
            templateName: mann-whitney
            requiredForCompletion: true
            args:
            - name: start-time
              value: "{{ experiment.availableAt }}"
            - name: end-time
              value: "{{ experiment.finishedAt }}"
            - name: stable-hash
              valueFrom:
                podTemplateHashValue: Stable
            - name: canary-hash
              valueFrom:
                podTemplateHashValue: Latest
      - setWeight: 1
      - pause:
          duration: 12
      - setWeight: 20
      - pause:
          duration: 12
      - setWeight: 40
      - pause:
          duration: 12
      - setWeight: 60
      - pause:
          duration: 12
      - setWeight: 80
      - pause:
          duration: 12
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-dropwizard
  labels:
    backstage.io/kubernetes-id: hello-world-dropwizard
spec:
  type: ClusterIP
  ports:
    - name: "hello-world-dropwizard"
      port: 8882
    - name: "hello-world-dropwizard-admin"
      port: 8883
  selector:
    app: hello-world-dropwizard
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: mann-whitney
spec:
  args:
  - name: start-time
  - name: end-time
  - name: stable-hash
  - name: canary-hash
  metrics:
  - name: mann-whitney
    interval: 30s
    failureLimit: 1
    count: 5
    provider:
      kayenta:
        address: http://kayenta-load-balancer.kayenta.svc.cluster.local:8090
        application: hello-world-dropwizard
        metricsAccountName: canary-prometheus
        canaryConfigName: canary-14
        configurationAccountName: in-memory-store-account
        storageAccountName: in-memory-store-account
        threshold:
          pass: 90
          marginal: 75
        scopes:
        - name: default
          controlScope:
            region: default
            scope: rolloutspodtemplatehash="{{args.stable-hash}}"
#            scope: app=hello-world-dropwizard and rollouts-pod-template-hash={{args.stable-hash}}
            step: 60
            start: "{{args.start-time}}"
            end: "{{args.end-time}}"
            region: "us-west-2"
          experimentScope:
            region: default
            scope: rolloutspodtemplatehash="{{args.canary-hash}}"
#            scope: app=hello-world-dropwizard and rollouts-pod-template-hash={{args.canary-hash}}
            step: 60
            start: "{{args.start-time}}"
            end: "{{args.end-time}}"
            region: "us-west-2"
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: aca-analyzer
spec:
  args:
  - name: start-time
  - name: end-time
  - name: stable-hash
  - name: canary-hash
  metrics:
  - name: aca-analyzer
    successCondition: result == true
    interval: 30s
    failureLimit: 1
    count: 5
    provider:
      web:
        url: "http://aca-analyzer.upwork-services.svc.cluster.local:8882/analysis/{{ args.stable-hash }}/{{ args.canary-hash }}"
        timeoutSeconds: 20 # defaults to 10 seconds
        jsonPath: "{$.data.ok}"
