apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-world-dropwizard
  labels:
    backstage.io/kubernetes-id: hello-world-dropwizard
spec:
  selector:
    matchLabels:
      app: hello-world-dropwizard
  replicas: 4
  template:
    metadata:
      labels:
        app: hello-world-dropwizard
        "backstage.io/kubernetes-id": "hello-world-dropwizard"
    spec:
      containers:
      - image: nicolasfagotti/hello-world-dropwizard:1.17.0
        name: hello-world-dropwizard
  strategy:
    canary:
      steps:
      - setWeight: 1
      - pause:
          duration: 10
      - setWeight: 10
      - pause:
          duration: 10
      - setWeight: 20
      - pause:
          duration: 10
      - setWeight: 30
      - pause:
          duration: 10
      - setWeight: 40
      - pause:
          duration: 10
      - setWeight: 50
      - pause: {}
      - setWeight: 60
      - pause:
          duration: 10
      - setWeight: 70
      - pause:
          duration: 10
      - setWeight: 80
      - pause:
          duration: 10
      - setWeight: 90
      - pause:
          duration: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-dropwizard
  labels:
    backstage.io/kubernetes-id: hello-world-dropwizard
spec:
  type: ClusterIP
  ports:
    - name: "hello-world-dropwizard"
      port: 8882
    - name: "hello-world-dropwizard-admin"
      port: 8883
  selector:
    app: hello-world-dropwizard
---
apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: example-experiment
spec:
  duration: 20m
  progressDeadlineSeconds: 60
  templates:
  - name: purple
    replicas: 1
    selector:
      matchLabels:
        app: canary-demo
        color: purple
    template:
      metadata:
        labels:
          app: canary-demo
          color: purple
      spec:
        containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:purple
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
  - name: orange
    replicas: 1
    minReadySeconds: 10
    selector:
      matchLabels:
        app: canary-demo
        color: orange
    template:
      metadata:
        labels:
          app: canary-demo
          color: orange
      spec:
        containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:orange
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
  analyses:
  - name: purple
    templateName: http-benchmark
    args:
    - name: host
      value: purple
  - name: orange
    templateName: http-benchmark
    args:
    - name: host
      value: orange
  - name: compare-results
    templateName: compare
    requiredForCompletion: true
    args:
    - name: host
      value: purple
