apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-world-dropwizard
spec:
  selector:
    matchLabels:
      app: hello-world-dropwizard
  replicas: 4
  template:
    metadata:
      labels:
        app: hello-world-dropwizard
        backstage.io/kubernetes-id: hello-world-dropwizard
    spec:
      containers:
      - image: nicolasfagotti/hello-world-dropwizard:1.17.0
        name: hello-world-dropwizard
  strategy:
    canary:
      steps:
      - setWeight: 1
      - pause:
          duration: 10
      - setWeight: 10
      - pause:
          duration: 10
      - setWeight: 20
      - pause:
          duration: 10
      - setWeight: 30
      - pause:
          duration: 10
      - setWeight: 40
      - pause:
          duration: 10
      - setWeight: 50
      - pause: {}
      - setWeight: 60
      - pause:
          duration: 10
      - setWeight: 70
      - pause:
          duration: 10
      - setWeight: 80
      - pause:
          duration: 10
      - setWeight: 90
      - pause:
          duration: 10

---

apiVersion: v1
kind: Service
metadata:
  name: hello-world-dropwizard
spec:
  type: ClusterIP
  ports:
    - name: "hello-world-dropwizard"
      port: 8882
    - name: "hello-world-dropwizard-admin"
      port: 8883
  selector:
    app: hello-world-dropwizard
