apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: aca-analyzer
  labels:
    backstage.io/kubernetes-id: aca-analyzer
spec:
  selector:
    matchLabels:
      app: aca-analyzer
  replicas: 2
  template:
    metadata:
      labels:
        app: aca-analyzer
        "backstage.io/kubernetes-id": "aca-analyzer"
    spec:
      containers:
      - image: nicolasfagotti/hello-world-dropwizard:1.17.5
        name: aca-analyzer
  strategy:
    canary:
      steps:
      - setWeight: 1
      - pause:
          duration: 10
      - setWeight: 10
      - pause:
          duration: 10
      - setWeight: 20
      - pause:
          duration: 10
      - setWeight: 30
      - pause:
          duration: 10
      - setWeight: 40
      - pause:
          duration: 10
      - setWeight: 50
      - pause: {}
      - setWeight: 60
      - pause:
          duration: 10
      - setWeight: 70
      - pause:
          duration: 10
      - setWeight: 80
      - pause:
          duration: 10
      - setWeight: 90
      - pause:
          duration: 10
---
apiVersion: v1
kind: Service
metadata:
  name: aca-analyzer
  labels:
    backstage.io/kubernetes-id: aca-analyzer
spec:
  type: ClusterIP
  ports:
    - name: "aca-analyzer"
      port: 8882
    - name: "aca-analyzer-admin"
      port: 8883
  selector:
    app: aca-analyzer
