apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-world-dropwizard
  labels:
    backstage.io/kubernetes-id: hello-world-dropwizard
spec:
  selector:
    matchLabels:
      app: hello-world-dropwizard
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world-dropwizard
        "backstage.io/kubernetes-id": "hello-world-dropwizard"
    spec:
      containers:
      - image: nicolasfagotti/hello-world-dropwizard:1.17.1
        name: hello-world-dropwizard
  strategy:
    canary:
      steps:
      - experiment:
          duration: 1h
          templates:
          - name: baseline
            specRef: stable
          - name: canary
            specRef: canary
          analyses:
          - name : gloster-success-rate
            templateName: gloster-success-rate
            args:
            - name: baseline-hash
              value: "{{templates.baseline.podTemplateHash}}"
            - name: canary-hash
              value: "{{templates.canary.podTemplateHash}}"
      - setWeight: 1
      - pause:
          duration: 10
      - setWeight: 10
      - pause:
          duration: 10
      - setWeight: 20
      - pause:
          duration: 10
      - setWeight: 30
      - pause:
          duration: 10
      - setWeight: 40
      - pause:
          duration: 10
      - setWeight: 50
      - pause: {}
      - setWeight: 60
      - pause:
          duration: 10
      - setWeight: 70
      - pause:
          duration: 10
      - setWeight: 80
      - pause:
          duration: 10
      - setWeight: 90
      - pause:
          duration: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-dropwizard
  labels:
    backstage.io/kubernetes-id: hello-world-dropwizard
spec:
  type: ClusterIP
  ports:
    - name: "hello-world-dropwizard"
      port: 8882
    - name: "hello-world-dropwizard-admin"
      port: 8883
  selector:
    app: hello-world-dropwizard
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: gloster-success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 5m
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.example.com:9090
        query: |
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.baseline-hash}}",response_code!~"5.*"}[5m]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.canary-hash}}"}[5m]
          ))
---
#apiVersion: argoproj.io/v1alpha1
#kind: Experiment
#metadata:
#  name: hello-world-experiment
#spec:
#  duration: 20m
#  progressDeadlineSeconds: 60
#  templates:
#  - name: version-1.17.0
#    replicas: 1
#    selector:
#      matchLabels:
#        app: canary-hello
#        version: vesion-0
#    template:
#      metadata:
#        labels:
#          app: canary-hello
#          version: version-0
#      spec:
#        containers:
#        - name: rollouts-hello
#          image: nicolasfagotti/hello-world-dropwizard:1.17.0
#          imagePullPolicy: Always
#          ports:
#          - name: http
#            containerPort: 8882
#            protocol: TCP
#  - name: version-1.17.1
#    replicas: 1
#    selector:
#      matchLabels:
#        app: canary-hello
#        version: version-1
#    template:
#      metadata:
#        labels:
#          app: canary-hello
#          version: version-1
#      spec:
#        containers:
#        - name: rollouts-hello
#          image: nicolasfagotti/hello-world-dropwizard:1.17.1
#          imagePullPolicy: Always
#          ports:
#          - name: http
#            containerPort: 8882
#            protocol: TCP
#  analyses:
#  - name: gloster
#    templateName: gloster-success-rate
#    args:
#    - name: service-name
#      value: helloWorld
#    - name: canary-release
#      value: testing-canary-pod-hash
#    - name: baseline-release
#      value: testing-baseline-pod-hash
