apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-dropwizard
spec:
  selector:
    matchLabels:
      app: hello-world-dropwizard
  template:
    metadata:
      labels:
        app: hello-world-dropwizard
    spec:
      containers:
      - image: nicolasfagotti/hello-world-dropwizard:1.0.17
        name: hello-world-dropwizard

---

apiVersion: v1
kind: Service
metadata:
  name: hello-world-dropwizard
spec:
  type: ClusterIP
  ports:
    - name: "hello-world-dropwizard"
      port: 8882
    - name: "hello-world-dropwizard-admin"
      port: 8883
  selector:
    app: hello-world-dropwizard

