apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-world-dropwizard
  labels:
    backstage.io/kubernetes-id: hello-world-dropwizard
spec:
  selector:
    matchLabels:
      app: hello-world-dropwizard
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world-dropwizard
        "backstage.io/kubernetes-id": "hello-world-dropwizard"
    spec:
      containers:
      - image: nicolasfagotti/hello-world-dropwizard:1.17.0
        name: hello-world-dropwizard
  strategy:
    canary:
      steps:
      - experiment:
          duration: 1h
          templates:
          - name: baseline
            specRef: stable
          - name: canary
            specRef: canary
          analyses:
          - name: mann-whitney
            templateName: mann-whitney
            args:
            - name: start-time
              value: "{{ experiment.availableAt }}"
            - name: end-time
              value: "{{ experiment.finishedAt }}"
            - name: stable-hash
              valueFrom:
                podTemplateHashValue: Stable
            - name: canary-hash
              valueFrom:
                podTemplateHashValue: Latest
      - setWeight: 1
      - pause:
          duration: 10
      - setWeight: 10
      - pause:
          duration: 10
      - setWeight: 20
      - pause:
          duration: 10
      - setWeight: 30
      - pause:
          duration: 10
      - setWeight: 40
      - pause:
          duration: 10
      - setWeight: 50
      - pause: {}
      - setWeight: 60
      - pause:
          duration: 10
      - setWeight: 70
      - pause:
          duration: 10
      - setWeight: 80
      - pause:
          duration: 10
      - setWeight: 90
      - pause:
          duration: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-dropwizard
  labels:
    backstage.io/kubernetes-id: hello-world-dropwizard
spec:
  type: ClusterIP
  ports:
    - name: "hello-world-dropwizard"
      port: 8882
    - name: "hello-world-dropwizard-admin"
      port: 8883
  selector:
    app: hello-world-dropwizard
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: gloster-success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 5m
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-operated.prometheus.svc.cluster.local:9090
        query: |
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.baseline-hash}}",response_code!~"5.*"}[5m]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.canary-hash}}"}[5m]
          ))
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: mann-whitney
spec:
  args:
  - name: start-time
  - name: end-time
  - name: stable-hash
  - name: canary-hash
  metrics:
  - name: mann-whitney
    provider:
      kayenta:
        address: http://kayenta-load-balancer.kayenta.svc.cluster.local:8090
        application: hello-world-dropwizard
        metricsAccountName: my-test
        configurationAccountName: my-test
        storageAccountName: my-test
        canaryConfigName: my-test
        threshold:
          pass: 90
          marginal: 75
        scopes:
        - name: default
          controlScope:
            region: default
            scope: app=hello-world-dropwizard and rollouts-pod-template-hash={{args.stable-hash}}
            step: 60
            start: "{{args.start-time}}"
            end: "{{args.end-time}}"
          experimentScope:
            region: default
            scope: app=hello-world-dropwizard and rollouts-pod-template-hash={{args.canary-hash}}
            step: 60
            start: "{{args.start-time}}"
            end: "{{args.end-time}}"
